//
//  Constants.h
//  Pods
//
//  Created by Med Kadhem Mansour on 6/17/20.
//

#ifndef Constants_h
#define Constants_h

FOUNDATION_EXPORT NSString *const MEDIA_ACTION_PAUSE=@"MEDIA_ACTION_PAUSE";
FOUNDATION_EXPORT NSString *const MEDIA_ACTION_PLAY=@"MEDIA_ACTION_PLAY";
FOUNDATION_EXPORT NSString *const MEDIA_ACTION_STOP=@"MEDIA_ACTION_STOP";
FOUNDATION_EXPORT NSString *const MEDIA_ACTION_CHANGE_STATE=@"MEDIA_ACTION_CHANGE_STATE";
FOUNDATION_EXPORT NSString *const MEDIA_ACTION_CHANGE_ITEM=@"MEDIA_ACTION_CHANGE_ITEM";
#endif /* Constants_h */
